
title: Aman Dwivedi

# User settings
url: "https://cherry0697.github.io/Portfolio/"
username: cherry0697
user_title: Sports Programmer
email: amanrevenge2811@gmail.com


google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
